[build]
builder = "nixpacks"
nixpacksPlan = { providers = ["python"], buildInputs = [] }

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
sleepApplication = false 